### ISSUE TITLE
Wrong tree structure

### ISSUE THREAD

**Issue by owodunni** [Rovanion/webgl-clojurescript-tutorial#1]
I get the following tree structure after doing "lein new figwheel webgl-clojurescript-tutorial"

.
├── project.clj
├── README
├── src
│   └── figwheel
│       └── core.clj
└── test
    └── figwheel
        └── test
            └── core.clj

**Comment by Rovanion** [comment]
It turned out that @owodunni was running Ubuntu 14.04 and had quite an old version of lein installed which for some reason resulted in him getting a really old version of the template.
