### ISSUE TITLE
Error when following tutorial

### ISSUE THREAD

**Issue by vushu** [Rovanion/webgl-clojurescript-tutorial#6]
Hi, when using this tutorial, i never managed to the **Let there be darkness**  part, since I am getting this following error.

```
----  Could not Analyze  resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc   line:437  column:41  ----

  Can't recur here at line 437 resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc

  435                          (set! (.-onselectstart canvas) (constantly false))
  436                          (if ctx ctx (recur (next ids))))
  437                        (catch js/Error e (recur (next ids))))))]
                                               ^--- Can't recur here at line 437 resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc
  438          (or ctx (err/unsupported! "WebGL not available"))))))
  439  #?(:clj
  440     (defn clear-color-buffer

----  Analysis Error : Please see resources/public/js/compiled/out/thi/ng/geom/gl/core.cljc  ----
```

**Comment by Rovanion** [comment]
Hmm, that's an error in the dependency Geom's code. Which version of geom are you depending on in your project.clj?

**Comment by vushu** [comment]
I am using [thi.ng/geom "0.0.1178-SNAPSHOT"]
I just did lein new figwheel foobar and added the dependency.
thanks.

**Comment by Rovanion** [comment]
Strange. If you clone the branch implementation and run it, what happens then?

https://github.com/Rovanion/webgl-clojurescript-tutorial/tree/implementation

**Comment by vushu** [comment]
The implementation branch works fine, hmm I think there are some problems using the latest figwheel template.
I think I will just use this configuration of project.clj.
When you have time, pls. look into the changes.
Thanks. :)

**Comment by Rovanion** [comment]
It would be great if you could look at the difference between your project and the implementation branch and perhaps figure out if there is one singular cause of this issue, perhaps just some piece of data in the project.clj.

**Comment by vushu** [comment]
Okay I manage to find the problem, I just changed the version my of clojurescript from [org.clojure/clojurescript "1.10.238"] to [org.clojure/clojurescript "1.9.89"]
Then it works, looks like the current version of thi.ng/geom isn't fully compatible with the latest clojurescript.

**Comment by Rovanion** [comment]
Thank you!

It's probably best to file a new bug against thing.geom then. Though I wouldn't necessarily expect it to be fixed by someone else, its creator seems to have moved on to other projects.

**Comment by vushu** [comment]
Yes I think I will create an issue about this for the creator, thank you for this guide :)

**Comment by Rovanion** [comment]
It was a joy to write.

If you'd like a challange there is a hidden bug in the guide where the shaders are created anew for each frame. If you would like a challenge you could try to find it and submit a PR with the fix. I've thought about fixing it for ages but never gotten to it, with the excuse that it could be left in as an extra exercise for the reader.

Cheerio!

**Comment by vushu** [comment]
The creator Karsten from thi.ng/geom said that I should try using this 
latest release candidate [thi.ng/geom "1.0.0-RC3"]
which works with the latest version of clojurescript.

Cheers. :)

**Comment by Rovanion** [comment]
Thank you!

**Comment by Rovanion** [comment]
I've pushed updated versions of the main and implementation branches to reflect your findings.

**Comment by vushu** [comment]
Cool thanks :D
